<script src="<?= base_url('assets/js/jquery.js?ver=<?php echo VERSION; ?>') ?>"></script>
<script src="<?= base_url('assets/js/bootstrap.min.js?ver=<?php echo VERSION; ?>') ?>"></script>
<script src="<?= base_url('assets/js/jquery.scrollUp.min.js?ver=<?php echo VERSION; ?>') ?>"></script>
<script src="<?= base_url('assets/js/price-range.js?ver=<?php echo VERSION; ?>') ?>"></script>
<script src="<?= base_url('assets/js/jquery.prettyPhoto.js?ver=<?php echo VERSION; ?>') ?>"></script>
<script src="<?= base_url('assets/js/main.js?ver=<?php echo VERSION; ?>') ?>"></script>
<script src="<?= base_url('assets/js/matrix.tables.js?ver=<?php echo VERSION; ?>') ?>"></script> 
<script src="<?= base_url('assets/js/matrix.popover.js?ver=<?php echo VERSION; ?>') ?>"></script> 
<script src="<?= base_url('assets/js/jquery.dataTables.min.js?ver=<?php echo VERSION; ?>') ?>"></script>  